# This rule is not used by the project cert-observer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over observer.cert-observer.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-observer
    app.kubernetes.io/managed-by: kustomize
  name: clusterobserver-admin-role
rules:
- apiGroups:
  - observer.cert-observer.io
  resources:
  - clusterobservers
  verbs:
  - '*'
- apiGroups:
  - observer.cert-observer.io
  resources:
  - clusterobservers/status
  verbs:
  - get
