apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
  namespace: default
spec:
  tls:
  - hosts:
    - shop.local
    secretName: shop-tls
  rules:
  - host: shop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shop
            port:
              number: 80
